### ISSUE TITLE
✨ Add a max player count on the handler page

### ISSUE THREAD

**Issue by mingdug** [SplitScreen-Me/splitscreenme-hub#100]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Problem

It just might be a bit easier for people to look at the handlers and the max player count if it was just on the general handler information (possibly under the image of the game) instead of having to go to the JS code since some newer people may not know to look there.

**Comment by Snailedlt** [comment]
Good idea!
Should be pretty easy to implement too since the info is already in the handler.
No one is working on the website atm afaik, so I'll add the help wanted label.
