### ISSUE TITLE
Fix grammatical error on front page

### ISSUE THREAD

**Issue by LineOf7s** [SplitScreen-Me/splitscreenme-hub#23]
![image](https://user-images.githubusercontent.com/28348332/127792645-54388512-c9ba-4fb7-90ee-ff527d8cfe64.png)

Easy one:  change it to "Games Hub" or "Game Hub".  No apostrophe, please.

**Comment by Snailedlt** [comment]
https://github.com/Snailedlt/splitscreenme-www/commit/58bf8fdeb5708e4012755695d7ec5c0bee566dc6
