### ISSUE TITLE
Add development setup to README.md

### ISSUE THREAD

**Issue by Snailedlt** [SplitScreen-Me/splitscreenme-hub#26]
Add a new section for development setup to the README.md file.

You can add the following to the top of the README:
-----
## Prerequisites
1. IDE or text editor. for example [WebStorm](https://www.jetbrains.com/webstorm/) or [VSCode](https://code.visualstudio.com/)
2. IDE for MongoDB, we recommend [NoSQLBooster](https://nosqlbooster.com/)

### Installation

```
$ npm install
```

### Local Development

```
$ npm run dev
```

This command starts a local development server and open up a browser window. Most changes are reflected live without having to restart the server.

**Comment by Lord-Baldwin-of-Kerry** [comment]
I think it would be wise to add the closed label to this issue :D

**Comment by Snailedlt** [comment]
Forgot to close this issue aswell.
Closed in #32
