### ISSUE TITLE
Increase the characters cap

### ISSUE THREAD

**Issue by BizzoZ** [SplitScreen-Me/splitscreenme-hub#57]
Hi guys,

If is possible, can you please Increase the characters cap for the "Your handler description" section?
I would love to make my handlers pages like a wiki and 3000 characters are not enough.

Thank you.

**Comment by Snailedlt** [comment]
Hi, I'm working on some QOL updates for the hub rn, and will include a fix for this.

How many lines characters do you need for a full guide?
I was thinking 10k lines would be good, is that fine by you?

**Comment by BizzoZ** [comment]
My intention was to create a wiki for each of my handlers. With different sections with tables and etc. 
The number of characters will depend on how many issues the specific handler has.

Anyway, 10k should be ok.

**Comment by BizzoZ** [comment]
My intention was to create a wiki for each of my handlers. With different sections with tables and etc. 
The number of characters will depend on how many issues the specific handler has.

Anyway, 10k should be ok.
